/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: {
          base: "var(--bg-base)",
          surface: "var(--bg-surface)",
          elevated: "var(--bg-elevated)",
          overlay: "var(--bg-overlay)",
          invert: "var(--bg-invert)",
        },
        text: {
          primary: "var(--text-primary)",
          secondary: "var(--text-secondary)",
          muted: "var(--text-muted)",
          disabled: "var(--text-disabled)",
          invert: "var(--text-invert)",
          code: "var(--text-code)",
          link: "var(--text-link)",
          linkHover: "var(--text-link-hover)",
        },
        accent: {
          mint: {
            DEFAULT: "var(--accent-mint)",
            dim: "var(--accent-mint-dim)",
            pale: "var(--accent-mint-pale)",
            glow: "var(--accent-mint-glow)",
            text: "var(--accent-mint-text)",
          },
          blue: {
            DEFAULT: "var(--accent-blue)",
            dim: "var(--accent-blue-dim)",
            pale: "var(--accent-blue-pale)",
            glow: "var(--accent-blue-glow)",
          },
          red: "var(--accent-red)",
          orange: "var(--accent-orange)",
          purple: "var(--accent-purple)",
        },
        domain: {
          ai: "var(--domain-ai)",
          web: "var(--domain-web)",
          android: "var(--domain-android)",
          uiux: "var(--domain-uiux)",
        },
        border: {
          subtle: "var(--border-subtle)",
          default: "var(--border-default)",
          emphasis: "var(--border-emphasis)",
          mint: "var(--border-mint)",
          focus: "var(--border-focus)",
        },
      },
      fontFamily: {
        display: ["var(--font-display)"],
        heading: ["var(--font-heading)"],
        body: ["var(--font-body)"],
        mono: ["var(--font-mono)"],
        label: ["var(--font-label)"],
      },
      spacing: {
        1: "var(--space-1)",
        2: "var(--space-2)",
        3: "var(--space-3)",
        4: "var(--space-4)",
        5: "var(--space-5)",
        6: "var(--space-6)",
        8: "var(--space-8)",
        10: "var(--space-10)",
        12: "var(--space-12)",
        16: "var(--space-16)",
        20: "var(--space-20)",
        24: "var(--space-24)",
        32: "var(--space-32)",
      },
      boxShadow: {
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        mintSm: "var(--shadow-mint-sm)",
        mintMd: "var(--shadow-mint-md)",
        mintLg: "var(--shadow-mint-lg)",
      },
      transitionTimingFunction: {
        default: "var(--ease-default)",
        in: "var(--ease-in)",
        out: "var(--ease-out)",
        spring: "var(--ease-spring)",
      },
      transitionDuration: {
        fast: "var(--duration-fast)",
        base: "var(--duration-base)",
        slow: "var(--duration-slow)",
        lazy: "var(--duration-lazy)",
      },
      zIndex: {
        below: "var(--z-below)",
        base: "var(--z-base)",
        raised: "var(--z-raised)",
        dropdown: "var(--z-dropdown)",
        sticky: "var(--z-sticky)",
        overlay: "var(--z-overlay)",
        modal: "var(--z-modal)",
        toast: "var(--z-toast)",
        cursor: "var(--z-cursor)",
      },
    },
  },
  plugins: [],
};
